name: Build and Test macOS App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode 16.0
        run: sudo xcode-select -s /Applications/Xcode_16.0.app

      - name: Build project
        run: |
          xcodebuild \
            -project ScriptBar.xcodeproj \
            -scheme ScriptBar \
            -destination 'platform=macOS' \
            clean build

      - name: Run tests
        run: |
          xcodebuild \
            -project ScriptBar.xcodeproj \
            -scheme ScriptBar \
            -destination 'platform=macOS' \
            test
